import { Indicator } from '@/app/types/indicator';

export const freeIndicators: Indicator[] = [
  {
    id: 'market-acceptance-envelope',
    title: 'Market Acceptance Envelope [Interakktive]',
    shortTitle: 'Market Acceptance Envelope',
    description: 'A dynamic envelope system that identifies institutional acceptance zones through probabilistic boundaries. Quantifies where price "belongs" based on statistical acceptance thresholds, revealing genuine support/resistance levels formed by market consensus rather than arbitrary technical levels.',
    features: [
      'Probabilistic acceptance boundaries (Bollinger-inspired methodology)',
      'Dynamic width adjustment based on volatility states',
      'Multi-standard deviation envelope layers',
      'Institutional acceptance zone identification',
      'Real-time boundary breach detection',
      'Customizable lookback and smoothing parameters',
    ],
    useCases: [
      'Identify high-probability reversal zones at envelope extremes',
      'Confirm trend strength when price sustains outside boundaries',
      'Detect compression phases when envelope narrows',
      'Validate breakouts when price establishes new acceptance ranges',
      'Support mean-reversion strategies in ranging markets',
    ],
    technicalDetails: 'Uses statistical standard deviation bands around a moving average baseline, with adaptive width calculations responding to realized volatility. Default: 20-period lookback with 2.0/2.5/3.0 standard deviation multipliers.',
    tradingViewUrl: 'https://www.tradingview.com/script/ZICs0t70-Market-Acceptance-Envelope-Interakktive/',
    category: 'free',
    stats: {
      uses: 2422,
      favorites: 511,
      publishedDate: 'December 25, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Market_Acceptance_Envelope_SS.png',
  },
  {
    id: 'market-state-intelligence',
    title: 'Market State Intelligence [Interakktive]',
    shortTitle: 'Market State Intelligence',
    description: 'A multi-dimensional regime classifier that synthesizes trend, momentum, volatility, and structure into unified market state intelligence. Provides real-time regime detection enabling traders to adapt strategies to current market conditions rather than applying static approaches across all environments.',
    features: [
      'Four-dimensional state analysis (Trend, Momentum, Volatility, Structure)',
      'Real-time regime classification system',
      'Composite market state scoring',
      'Visual state transition alerts',
      'Historical regime performance tracking',
      'Customizable dimension weights and thresholds',
    ],
    useCases: [
      'Adapt trading strategies based on current market regime',
      'Identify regime transitions before they fully develop',
      'Filter trade signals based on favorable market states',
      'Understand why certain strategies perform in specific conditions',
      'Build regime-conditional trading systems',
    ],
    technicalDetails: 'Combines normalized metrics across four dimensions: ADX-based trend strength, RSI momentum, ATR volatility states, and swing structure analysis. Outputs composite regime scores for trending, ranging, volatile, and calm states.',
    tradingViewUrl: 'https://www.tradingview.com/script/I1eqEIHI-Market-State-Intelligence-Interakktive/',
    category: 'free',
    stats: {
      uses: 660,
      favorites: 2311,
      publishedDate: 'December 25, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Market_State_Intelligence_SS.png',
  },
  {
    id: 'market-acceptance-zones',
    title: 'Market Acceptance Zones [Interakktive]',
    shortTitle: 'Market Acceptance Zones',
    description: 'Identifies institutional acceptance levels where significant volume concentration and price equilibrium occurs. Maps horizontal zones representing areas of sustained interest rather than transient price levels, revealing where smart money has established positions.',
    features: [
      'Volume-weighted acceptance level detection',
      'Time-at-price concentration analysis',
      'Dynamic zone width based on institutional activity',
      'Support/Resistance level validation',
      'Historical zone strength persistence tracking',
      'Multi-timeframe zone confluence detection',
    ],
    useCases: [
      'Identify high-probability reversal zones at established acceptance levels',
      'Validate breakout potential when price exits acceptance zones',
      'Find institutional entry/exit areas based on volume concentration',
      'Set strategic stop-loss placements outside acceptance boundaries',
      'Detect accumulation/distribution zones through sustained price action',
    ],
    technicalDetails: 'Combines volume profile analysis with time-weighted price distribution to identify statistically significant acceptance zones. Uses clustering algorithms to group nearby levels into coherent institutional zones.',
    tradingViewUrl: 'https://www.tradingview.com/script/yZ4KaZk4-Market-Acceptance-Zones-Interakktive/',
    category: 'free',
    stats: {
      views: 21811,
      favorites: 2532,
      publishedDate: 'December 23, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Market_Acceptance_Zones_SS.png',
  },
  {
    id: 'market-participation-gradient',
    title: 'Market Participation Gradient [Interakktive]',
    shortTitle: 'Market Participation Gradient',
    description: 'Tracks the intensity and directional bias of market participation through momentum pressure analysis. Measures whether participation is accelerating (conviction building) or decelerating (conviction fading), revealing the commitment level behind price movements.',
    features: [
      'Momentum pressure intensity measurement',
      'Directional participation bias detection',
      'Acceleration/Deceleration gradient analysis',
      'Conviction strength quantification',
      'Visual participation heat mapping',
      'Divergence detection between price and participation',
    ],
    useCases: [
      'Confirm trend strength through rising participation gradients',
      'Detect early weakness when participation decelerates despite price advance',
      'Identify exhaustion zones where participation peaks',
      'Validate reversals when participation shifts directional bias',
      'Filter low-conviction moves with weak participation',
    ],
    technicalDetails: 'Combines rate-of-change calculations across multiple timeframes with momentum oscillators to create a composite participation gradient. Measures both magnitude and acceleration of momentum shifts.',
    tradingViewUrl: 'https://www.tradingview.com/script/CxnjSZB9-Market-Participation-Gradient-Interakktive/',
    category: 'free',
    stats: {
      uses: 365,
      favorites: 1611,
      publishedDate: 'December 22, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Market_Participation_Gradient_SS.png',
  },
  {
    id: 'market-pressure-regime',
    title: 'Market Pressure Regime [Interakktive]',
    shortTitle: 'Market Pressure Regime',
    description: 'A multi-dimensional pressure state classifier that identifies whether current market conditions favor buyers, sellers, or equilibrium. Synthesizes buying pressure, selling pressure, and equilibrium metrics into actionable regime states for strategy adaptation.',
    features: [
      'Three-dimensional pressure analysis (Buy/Sell/Equilibrium)',
      'Real-time regime classification system',
      'Pressure intensity scoring (0-100 scale)',
      'Visual pressure state zones',
      'Regime transition alerts',
      'Historical pressure pattern recognition',
    ],
    useCases: [
      'Identify dominant market pressure regimes in real-time',
      'Detect regime shifts before price fully reflects them',
      'Adapt directional bias based on pressure dominance',
      'Avoid counter-trend trades in strong pressure regimes',
      'Recognize equilibrium zones for range-bound strategies',
    ],
    technicalDetails: 'Combines buying/selling volume analysis, momentum directional strength, and price action equilibrium patterns. Outputs normalized pressure scores across three dimensions with composite regime classification.',
    tradingViewUrl: 'https://www.tradingview.com/script/V3jfGrc1-Market-Pressure-Regime-Interakktive/',
    category: 'free',
    stats: {
      uses: 486,
      favorites: 1511,
      publishedDate: 'December 19, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Market_Pressure_Regime_SS.png',
  },
  {
    id: 'volatility-state-index',
    title: 'Volatility State Index [Interakktive]',
    shortTitle: 'Volatility State Index',
    description: 'A comprehensive volatility regime detection system that classifies current market conditions into distinct volatility states. Enables traders to adjust position sizing, stop-loss placement, and strategy selection based on realized volatility environments.',
    features: [
      'Multi-state volatility classification (Calm/Normal/Elevated/Extreme)',
      'Normalized volatility scoring (0-100)',
      'Historical volatility percentile ranking',
      'Volatility expansion/contraction detection',
      'Visual volatility regime zones',
      'Adaptive threshold calculations',
    ],
    useCases: [
      'Adjust position sizing based on current volatility regime',
      'Widen stops in elevated volatility, tighten in calm states',
      'Identify volatility expansion preceding major moves',
      'Detect compression zones for potential breakout setups',
      'Adapt strategy parameters to volatility environment',
    ],
    technicalDetails: 'Uses ATR (Average True Range) with percentile ranking against historical lookback to classify volatility states. Includes smoothing to prevent false regime flipping and adaptive threshold calculations.',
    tradingViewUrl: 'https://www.tradingview.com/script/7K0MaDFs-Volatility-State-Index-Interakktive/',
    category: 'free',
    stats: {
      uses: 480,
      favorites: 2511,
      publishedDate: 'December 19, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Volitality_State_Index_SS.png',
  },
  {
    id: 'effort-result-divergence',
    title: 'Effort-Result Divergence [Interakktive]',
    shortTitle: 'Effort-Result Divergence',
    description: 'A Wyckoff-inspired analytical tool that identifies efficiency anomalies by comparing volume effort against price result. Detects conditions where high volume produces minimal price movement (inefficiency) or low volume produces significant movement (abnormal efficiency), revealing potential institutional activity.',
    features: [
      'Volume-Price efficiency ratio calculation',
      'Effort-Result divergence detection',
      'Institutional activity anomaly identification',
      'Efficiency/Inefficiency zone mapping',
      'Visual divergence alerts',
      'Customizable sensitivity thresholds',
    ],
    useCases: [
      'Identify accumulation zones where high volume produces minimal downside',
      'Detect distribution patterns with large volume but limited upside',
      'Recognize potential reversals at extreme effort-result divergences',
      'Validate breakouts when volume effort aligns with price result',
      'Spot institutional positioning through efficiency anomalies',
    ],
    technicalDetails: 'Calculates efficiency ratio by comparing normalized volume intensity to normalized price displacement. Detects statistical outliers representing significant effort-result mismatches using z-score methodology.',
    tradingViewUrl: 'https://www.tradingview.com/script/kb56fTI3-Effort-Result-Divergence-Interakktive/',
    category: 'free',
    stats: {
      uses: 549,
      favorites: 2311,
      publishedDate: 'December 18, 2025',
      updatedDate: 'December 19, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Effort_Result_Divergence_SS.png',
  },
  {
    id: 'market-efficiency-ratio',
    title: 'Market Efficiency Ratio [Interakktive]',
    shortTitle: 'Market Efficiency Ratio',
    description: 'A diagnostic tool that decomposes price movement into directional progress versus wasted oscillatory movement. Quantifies what proportion of price\'s total travel distance represented genuine directional advancement versus sideways chop, enabling traders to differentiate trending efficiency from consolidation waste.',
    features: [
      'Efficiency Ratio calculation (0-100 scale)',
      'Net Displacement measurement',
      'Path Length tracking (total distance traveled)',
      'Chop Cost quantification',
      'Visual efficiency zones (Green ≥70%, Yellow 30-70%, Red <30%)',
      'Customizable lookback and smoothing parameters',
    ],
    useCases: [
      'Differentiate clean trending periods from messy consolidation phases',
      'Understand relationship between total movement and productive progress',
      'Identify high-chop environments presenting elevated trading difficulty',
      'Assess trend quality without volume dependence',
      'Support foundation work for advanced regime detection systems',
    ],
    technicalDetails: 'Net Displacement = |Close[current] - Close[N bars back]|; Path Length = Sum of bar-to-bar absolute changes; Efficiency Ratio = Net Displacement ÷ Path Length; Chop Cost = Path Length - Net Displacement. Default: 14-bar lookback, 5-bar EMA smoothing.',
    tradingViewUrl: 'https://www.tradingview.com/script/e1LSxUSp-Market-Efficiency-Ratio-Interakktive/',
    category: 'free',
    stats: {
      uses: 2411,
      favorites: 450,
      publishedDate: 'December 18, 2025',
      updatedDate: 'December 19, 2025',
    },
    isPro: false,
    isPublished: true,
    image: '/images/Market_Efficiency_Ration_SS.png',
  },
];

export const proIndicators: Indicator[] = [
  {
    id: 'atlas-cipher-pro',
    title: 'ATLAS - CIPHER PRO [Interakktive]',
    shortTitle: 'ATLAS - CIPHER PRO',
    description: 'A comprehensive AI/ML-enabled trading system featuring Ghost Performance tracking, Adaptive Quality thresholds, Multi-Timeframe Confluence, intelligent Exit Signals, and Risk Ribbon visualization. The flagship indicator of the INTERAKKTIVE - ATLAS suite, combining multiple analytical dimensions into a unified decision support system.',
    features: [
      'Ghost Performance Tracking - Historical win rate analysis for similar setups',
      'Adaptive Quality Threshold - Auto-adjusts minimum quality based on performance',
      'Multi-Timeframe Confluence - Higher timeframe alignment scoring (+10 bonus)',
      'Win Probability Estimator - Shows percentage with sample size (e.g., "73% (142)")',
      'Intelligent Exit Signals - Optimized profit-taking and stop-loss management',
      'Risk Ribbon - Visual risk state classification',
      'Regime Detection - Market state adaptation',
      'Real-time Quality Scoring - Trade setup quality quantification',
    ],
    useCases: [
      'Execute high-probability setups with AI-validated quality scores',
      'Leverage multi-timeframe alignment for enhanced conviction',
      'Adapt strategy based on real-time win probability estimates',
      'Optimize exits using intelligent signal management',
      'Track and improve performance through Ghost analytics',
    ],
    technicalDetails: 'v1.1.9.3 includes MTF Quality Bonus (+10 both aligned, +5 one aligned), MTF Quality Penalty (-10 both against, -5 one against), MTF TP Probability (+8% aligned, -5% against), Adaptive Quality Threshold (auto-adjusts based on Ghost win rate), and Win Probability with sample size display.',
    tradingViewUrl: '',
    category: 'pro',
    stats: {
      favorites: 0,
      publishedDate: 'Not yet published',
    },
    isPro: true,
    isPublished: false,
    image: 'https://placehold.co/1200x800/0d1117/fbbf24?text=ATLAS+CIPHER\\nPRO',
  },
];

export const allIndicators = [...freeIndicators, ...proIndicators];

export function getIndicatorById(id: string): Indicator | undefined {
  return allIndicators.find(indicator => indicator.id === id);
}

export function getFreeIndicators(): Indicator[] {
  return freeIndicators;
}

export function getProIndicators(): Indicator[] {
  return proIndicators;
}
