// app/academy/lesson/market-structure-smc/page.tsx
// ATLAS Academy — Lesson 3.2: Market Structure Mastery [PRO]
'use client';

import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import { Crown, ArrowRight, ChevronDown } from 'lucide-react';

function seededRandom(seed: number): () => number {
  let s = seed;
  return () => { s = (s * 16807) % 2147483647; return s / 2147483647; };
}

function genBullishStructure(seed: number): { prices: number[]; swings: { idx: number; type: 'HH' | 'HL' | 'LH' | 'LL' }[] } {
  const rand = seededRandom(seed); const p: number[] = [100]; const swings: { idx: number; type: 'HH' | 'HL' | 'LH' | 'LL' }[] = []; let price = 100;
  const levels: { target: number; type: 'HH' | 'HL' | 'LH' | 'LL' }[] = [{target:106,type:'HH'},{target:103,type:'HL'},{target:110,type:'HH'},{target:106.5,type:'HL'},{target:114,type:'HH'},{target:109,type:'HL'},{target:117,type:'HH'}];
  for (const lv of levels) { const steps = 6 + Math.floor(rand() * 4); for (let i = 0; i < steps; i++) { const progress = (i+1)/steps; price = price + (lv.target-price)*progress*0.4 + (rand()-0.5)*1; p.push(price); } price = lv.target + (rand()-0.5)*0.5; p.push(price); swings.push({idx:p.length-1,type:lv.type}); }
  return { prices: p, swings };
}

function genBearishStructure(seed: number): { prices: number[]; swings: { idx: number; type: 'HH' | 'HL' | 'LH' | 'LL' }[] } {
  const rand = seededRandom(seed); const p: number[] = [115]; const swings: { idx: number; type: 'HH' | 'HL' | 'LH' | 'LL' }[] = []; let price = 115;
  const levels: { target: number; type: 'HH' | 'HL' | 'LH' | 'LL' }[] = [{target:110,type:'LL'},{target:113,type:'LH'},{target:107,type:'LL'},{target:110,type:'LH'},{target:103,type:'LL'},{target:106,type:'LH'},{target:100,type:'LL'}];
  for (const lv of levels) { const steps = 6 + Math.floor(rand() * 4); for (let i = 0; i < steps; i++) { const progress = (i+1)/steps; price = price + (lv.target-price)*progress*0.4 + (rand()-0.5)*1; p.push(price); } price = lv.target + (rand()-0.5)*0.5; p.push(price); swings.push({idx:p.length-1,type:lv.type}); }
  return { prices: p, swings };
}

function genGameScenario(type: string, seed: number): number[] {
  const rand = seededRandom(seed); const p: number[] = []; let price = type === 'bos_bear' || type === 'range' ? 115 : 100;
  p.push(price);
  if (type === 'bos_bull') { for (let i=0;i<10;i++){price+=0.5+(rand()-0.4)*1;p.push(price);} for(let i=0;i<6;i++){price-=0.3+(rand()-0.5)*0.6;p.push(price);} for(let i=0;i<10;i++){price+=0.6+(rand()-0.4)*0.8;p.push(price);} for(let i=0;i<5;i++){price+=0.3+(rand()-0.5)*0.8;p.push(price);} }
  else if (type === 'choch_bear') { for(let i=0;i<8;i++){price+=0.5+(rand()-0.4)*1;p.push(price);} for(let i=0;i<5;i++){price-=0.3+(rand()-0.5)*0.5;p.push(price);} for(let i=0;i<6;i++){price+=0.2+(rand()-0.5)*0.6;p.push(price);} for(let i=0;i<8;i++){price-=0.5+(rand()-0.4)*0.8;p.push(price);} for(let i=0;i<6;i++){price-=0.4+(rand()-0.5)*0.8;p.push(price);} }
  else if (type === 'bos_bear') { for(let i=0;i<10;i++){price-=0.5+(rand()-0.4)*1;p.push(price);} for(let i=0;i<6;i++){price+=0.3+(rand()-0.5)*0.6;p.push(price);} for(let i=0;i<10;i++){price-=0.6+(rand()-0.4)*0.8;p.push(price);} for(let i=0;i<5;i++){price-=0.3+(rand()-0.5)*0.8;p.push(price);} }
  else if (type === 'mss') { for(let i=0;i<12;i++){price+=0.5+(rand()-0.4)*1;p.push(price);} for(let i=0;i<10;i++){price-=0.6+(rand()-0.4)*0.8;p.push(price);} for(let i=0;i<5;i++){price+=0.2+(rand()-0.5)*0.5;p.push(price);} for(let i=0;i<10;i++){price-=0.5+(rand()-0.4)*0.8;p.push(price);} }
  else { for(let i=0;i<40;i++){price+=(rand()-0.5)*2;price=Math.max(100,Math.min(110,price));p.push(price);} }
  return p;
}

function AnimScene({drawFn,height=300}:{drawFn:(ctx:CanvasRenderingContext2D,w:number,h:number,f:number)=>void;height?:number}){const canvasRef=useRef<HTMLCanvasElement>(null);const frameRef=useRef(0);const animRef=useRef(0);useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.scale(dpr,dpr);const loop=()=>{ctx.clearRect(0,0,rect.width,rect.height);drawFn(ctx,rect.width,rect.height,frameRef.current);frameRef.current++;animRef.current=requestAnimationFrame(loop);};loop();return()=>cancelAnimationFrame(animRef.current);},[drawFn]);return <canvas ref={canvasRef} style={{width:'100%',height}} className="rounded-2xl" />;}

function StaircaseAnimation(){const draw=useCallback((ctx:CanvasRenderingContext2D,w:number,h:number,f:number)=>{ctx.fillStyle='rgba(6,10,18,0.95)';ctx.fillRect(0,0,w,h);const progress=Math.min((f%300)/200,1);const steps=[{x:0.08,y:0.82,label:'HL\u2081',isHigh:false},{x:0.22,y:0.65,label:'HH\u2081',isHigh:true},{x:0.36,y:0.58,label:'HL\u2082',isHigh:false},{x:0.50,y:0.40,label:'HH\u2082',isHigh:true},{x:0.64,y:0.35,label:'HL\u2083',isHigh:false},{x:0.78,y:0.18,label:'HH\u2083',isHigh:true}];const vc=Math.floor(steps.length*progress)+1;ctx.beginPath();ctx.strokeStyle='#0ea5e9';ctx.lineWidth=2.5;ctx.shadowColor='#0ea5e9';ctx.shadowBlur=6;for(let i=0;i<Math.min(vc,steps.length);i++){const x=steps[i].x*w;const y=steps[i].y*h;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();ctx.shadowBlur=0;for(let i=0;i<Math.min(vc,steps.length);i++){const s=steps[i];const x=s.x*w;const y=s.y*h;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fillStyle=s.isHigh?'#22c55e':'#0ea5e9';ctx.fill();ctx.fillStyle=s.isHigh?'#22c55e':'#0ea5e9';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText(s.label,x,s.isHigh?y-12:y+18);}if(vc>=4){ctx.setLineDash([3,3]);ctx.strokeStyle='rgba(34,197,94,0.2)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(steps[1].x*w,steps[1].y*h);ctx.lineTo(steps[3].x*w,steps[1].y*h);ctx.stroke();ctx.fillStyle='#22c55e';ctx.font='9px system-ui';ctx.textAlign='center';ctx.fillText('\u2191 Higher',(steps[1].x+steps[3].x)/2*w,steps[1].y*h-5);ctx.setLineDash([]);}ctx.fillStyle='#f59e0b';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText('BULLISH STRUCTURE: Higher Highs + Higher Lows',w/2,16);if(progress>0.8){ctx.globalAlpha=Math.min((progress-0.8)*5,1);ctx.fillStyle='#9ca3af';ctx.font='9px system-ui';ctx.fillText('Like a staircase going UP \u2014 each step is higher than the last',w/2,h-8);ctx.globalAlpha=1;}},[]);return <AnimScene drawFn={draw} height={250} />;}

function StructureChart({prices,swings,height=300,showLabels=true}:{prices:number[];swings?:{idx:number;type:string}[];height?:number;showLabels?:boolean}){const canvasRef=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.scale(dpr,dpr);const w=rect.width,h=rect.height;ctx.fillStyle='#060a12';ctx.fillRect(0,0,w,h);const pMin=Math.min(...prices)-1;const pMax=Math.max(...prices)+1;const pRange=pMax-pMin;const len=prices.length;const px=(i:number)=>15+(i/(len-1))*(w-30);const py=(p:number)=>20+(h-40)*(1-(p-pMin)/pRange);ctx.beginPath();ctx.strokeStyle='#0ea5e9';ctx.lineWidth=2;for(let i=0;i<len;i++){i===0?ctx.moveTo(px(i),py(prices[i])):ctx.lineTo(px(i),py(prices[i]));}ctx.stroke();if(showLabels&&swings){for(const s of swings){if(s.idx>=len)continue;const x=px(s.idx);const y=py(prices[s.idx]);const isHigh=s.type==='HH'||s.type==='LH';const color=s.type==='HH'?'#22c55e':s.type==='HL'?'#0ea5e9':s.type==='LH'?'#f59e0b':'#ef4444';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.fillStyle=color;ctx.font='bold 9px system-ui';ctx.textAlign='center';ctx.fillText(s.type,x,isHigh?y-10:y+16);}}},[prices,swings,height,showLabels]);return <canvas ref={canvasRef} style={{width:'100%',height}} className="rounded-xl bg-[#060a12]" />;}

export default function MarketStructureSMCLesson(){const[scrollY,setScrollY]=useState(0);const[structView,setStructView]=useState<'bullish'|'bearish'>('bullish');const[bosStep,setBosStep]=useState(0);const bullData=useMemo(()=>genBullishStructure(42),[]);const bearData=useMemo(()=>genBearishStructure(77),[]);
const demoSteps=useMemo(()=>[{title:'Uptrend in progress',desc:'Price is making Higher Highs and Higher Lows. Structure is bullish. We trust the trend until structure BREAKS.',highlight:'none'},{title:'Break of Structure (BOS)',desc:'Price makes a new Higher High \u2014 breaking above the previous swing high. This is a BOS. It CONFIRMS the uptrend is continuing. BOS = "the trend is still alive." Every new HH in an uptrend is a BOS.',highlight:'bos'},{title:'Pullback to Higher Low',desc:'Price pulls back but holds above the previous low \u2014 creating a new Higher Low. The staircase structure remains intact. This pullback is your ENTRY ZONE.',highlight:'hl'},{title:'Change of Character (CHoCH)',desc:'Price fails to make a new HH, then breaks BELOW the most recent Higher Low. This is a CHoCH \u2014 the FIRST sign that the trend might be dying. CHoCH = "something has changed." It doesn\'t guarantee reversal, but it\'s the first warning shot.',highlight:'choch'},{title:'Market Structure Shift (MSS)',desc:'After the CHoCH, price now makes a Lower High AND breaks below the previous low \u2014 creating a Lower Low. This is MSS = full reversal CONFIRMED. The uptrend is dead. A new downtrend has begun.',highlight:'mss'}],[]);
const gamePatterns=useMemo(()=>['bos_bull','choch_bear','bos_bear','mss','range'],[]);const gamePrices=useMemo(()=>gamePatterns.map((t,i)=>genGameScenario(t,400+i*53)),[gamePatterns]);const gameOptions=['Bullish BOS (trend continues up)','Bearish CHoCH (trend changing)','Bearish BOS (downtrend continues)','Market Structure Shift (full reversal)','No clear structure (ranging)'];const gameCorrectIdx=[0,1,2,3,4];
const[gameRound,setGameRound]=useState(0);const[gameAnswers,setGameAnswers]=useState<(number|null)[]>(Array(5).fill(null));const[gameScore,setGameScore]=useState(0);const[gameShowNext,setGameShowNext]=useState(false);const[gameComplete,setGameComplete]=useState(false);
const gameExplanations=['Price was in an uptrend (HH-HL pattern), pulled back, then broke above the previous high. That\'s a bullish Break of Structure \u2014 the uptrend is confirmed and continuing.','Price was making higher highs, then failed to make a new HH and broke below the most recent Higher Low. That\'s the first sign of character changing \u2014 a CHoCH. Buyers are losing control.','Price was in a downtrend (LH-LL pattern), bounced weakly, then broke below the previous low. Bearish BOS \u2014 the downtrend is confirmed and continuing.','Price was trending up, then made a lower high AND broke a lower low \u2014 complete structure flip. The uptrend is dead, replaced by bearish structure. This is a full Market Structure Shift.','Price is bouncing between roughly the same highs and lows \u2014 no higher highs, no lower lows. This is a range/consolidation. There\'s no clear structure to trade. Wait for a breakout.'];
const answerGame=(choice:number)=>{if(gameAnswers[gameRound]!==null)return;const na=[...gameAnswers];na[gameRound]=choice;setGameAnswers(na);if(choice===gameCorrectIdx[gameRound])setGameScore(s=>s+1);setGameShowNext(true);};const nextRound=()=>{if(gameRound<4){setGameRound(r=>r+1);setGameShowNext(false);}else setGameComplete(true);};const resetGame=()=>{setGameRound(0);setGameAnswers(Array(5).fill(null));setGameScore(0);setGameShowNext(false);setGameComplete(false);};
const quizQuestions=useMemo(()=>[{q:'Bullish market structure consists of:',opts:['Lower Highs and Lower Lows','Higher Highs and Higher Lows','Equal Highs and Equal Lows','Random price movement'],a:1,explain:'Bullish = staircase going up. Each high is HIGHER than the last (HH), and each low is HIGHER than the last (HL).'},{q:'A Break of Structure (BOS) in an uptrend occurs when:',opts:['Price breaks below a previous low','Price makes a new Higher High \u2014 breaking above the previous swing high','Price goes sideways','Volume increases'],a:1,explain:'BOS = price breaks past a previous swing point IN THE DIRECTION of the trend. In an uptrend, a new HH that exceeds the previous HH is a bullish BOS.'},{q:'What is a Change of Character (CHoCH)?',opts:['When the market opens at a different time','The FIRST break of structure AGAINST the current trend','A very large candle','When volume doubles'],a:1,explain:'CHoCH is the first crack in the structure. In an uptrend, it\'s when price breaks below the most recent Higher Low for the first time.'},{q:'What is the difference between CHoCH and MSS?',opts:['They\'re the same thing','CHoCH is the first warning; MSS is the confirmed reversal with structure in the opposite direction','MSS happens on higher timeframes only','CHoCH is bearish, MSS is bullish'],a:1,explain:'CHoCH = first crack (warning). MSS = confirmed flip (structure now established in opposite direction).'},{q:'In a downtrend, a bearish BOS occurs when:',opts:['Price makes a new Higher High','Price breaks below the previous Lower Low','Price bounces from support','RSI enters oversold'],a:1,explain:'In a downtrend, BOS = new Lower Low breaking below the previous swing low. Each new LL confirms the downtrend.'},{q:'"Internal structure" refers to:',opts:['The structure of a single candlestick','Smaller swing highs/lows WITHIN a larger structural move \u2014 fractal structure','Support and resistance levels','The bid-ask spread'],a:1,explain:'Markets are fractal \u2014 structure exists within structure. Internal structure on the LTF helps time entries within the larger HTF moves.'},{q:'Price is in an uptrend. It pulls back but holds above the previous swing low. What happened?',opts:['A bullish BOS','A bearish CHoCH','Nothing \u2014 a Higher Low formed, trend is intact','A Market Structure Shift'],a:2,explain:'The pullback held above the previous low = Higher Low. The bullish structure is intact. No structure broken.'},{q:'Why is market structure THE most important concept in Smart Money trading?',opts:['It\'s the most complicated','Without knowing structure, you can\'t identify BOS, CHoCH, OBs, or any other SMC concept','It only matters on the daily chart','It replaces all indicators'],a:1,explain:'Structure is the SKELETON of the market. Every other SMC concept depends on knowing the current structure.'}],[]);
const[quizAnswers,setQuizAnswers]=useState<(number|null)[]>(Array(8).fill(null));const quizDone=quizAnswers.every(a=>a!==null);const score=quizDone?Math.round((quizAnswers.filter((a,i)=>a===quizQuestions[i].a).length/quizQuestions.length)*100):0;const certUnlocked=quizDone&&score>=66;
useEffect(()=>{const onScroll=()=>setScrollY(window.scrollY);window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll);},[]);

return(<div className="min-h-screen text-white" style={{background:'linear-gradient(to bottom, #060a12, #0a0f1a)'}}>
<div className="fixed top-0 left-0 right-0 z-50 h-1 bg-gray-900/50"><motion.div className="h-full bg-gradient-to-r from-amber-500 to-accent-500" style={{width:`${Math.min((scrollY/(typeof document!=='undefined'?document.body.scrollHeight-window.innerHeight:1))*100,100)}%`}} /></div>
<nav className="sticky top-0 z-40 px-5 py-3 flex items-center justify-between" style={{background:'rgba(6,10,18,0.85)',backdropFilter:'blur(16px)'}}><Link href="/academy" className="text-xs text-gray-500 hover:text-gray-300 transition">&larr; Academy</Link><div className="flex items-center gap-2"><Crown className="w-3.5 h-3.5 text-amber-400" /><span className="text-xs font-bold text-amber-400">PRO &middot; LEVEL 3</span></div></nav>

<section className="px-5 pt-16 pb-12 text-center"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><p className="text-xs font-semibold tracking-widest uppercase text-amber-400 mb-3">Level 3 &middot; Lesson 2</p><h1 className="text-4xl sm:text-5xl font-black mb-4 leading-tight"><span className="bg-gradient-to-r from-red-400 via-amber-400 to-primary-400 bg-clip-text text-transparent" style={{WebkitTransform:'translateZ(0)'}}>Market Structure<br/>Mastery</span></h1><p className="text-gray-400 text-base max-w-md mx-auto leading-relaxed">BOS, CHoCH, and MSS &mdash; the language institutions speak. Learn to read the skeleton of every chart.</p></motion.div></section>

<section className="px-5 py-12 max-w-2xl mx-auto"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="text-xs font-bold tracking-widest uppercase text-amber-400 mb-6">First &mdash; Why This Matters</p><div className="p-6 rounded-2xl glass-card mb-6"><p className="text-lg font-bold text-white mb-3">&#127959;&#65039; Every building has a skeleton. Every chart has structure.</p><p className="text-gray-400 leading-relaxed mb-4">Before you can hang paintings (indicators), install plumbing (strategies), or paint walls (entries) &mdash; you need the skeleton. In trading, <strong className="text-white">market structure IS that skeleton.</strong> It tells you who is currently in control &mdash; buyers or sellers.</p><p className="text-gray-400 leading-relaxed mb-4">Structure is deceptively simple: price either makes <strong className="text-green-400">Higher Highs + Higher Lows</strong> (buyers winning) or <strong className="text-red-400">Lower Highs + Lower Lows</strong> (sellers winning). When that pattern BREAKS, power is shifting.</p><p className="text-gray-400 leading-relaxed"><strong className="text-amber-400">Without structure, nothing else in Level 3 makes sense.</strong> Order blocks, FVGs, liquidity &mdash; they all depend on knowing the current structure.</p></div><StaircaseAnimation /><div className="mt-6 p-5 rounded-2xl border border-amber-500/20 bg-amber-500/5"><p className="text-xs font-bold text-amber-400 mb-2">&#128270; REAL SCENARIO</p><p className="text-sm text-gray-300 leading-relaxed">XAUUSD made Higher Highs at $2,050, $2,075, $2,090 over three weeks. Then price dropped below the recent Higher Low at $2,060. That was the <strong className="text-red-400">CHoCH</strong>. Two days later, a Lower Low below $2,040. <strong className="text-red-400">MSS confirmed</strong> &mdash; traders who read structure sold at $2,055 and rode Gold down to $1,985. <em className="text-amber-400">A $70 move predicted by two letters: CHoCH.</em></p></div></motion.div></section>

<section className="px-5 py-12 max-w-2xl mx-auto"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">01 &mdash; The Two Structures</p><h2 className="text-2xl font-extrabold mb-4">Bullish vs Bearish Structure</h2><div className="flex gap-2 mb-4"><button onClick={()=>setStructView('bullish')} className={`flex-1 py-2.5 rounded-xl text-xs font-bold transition-all ${structView==='bullish'?'bg-green-500 text-black':'glass text-gray-400'}`}>&uarr; Bullish (HH + HL)</button><button onClick={()=>setStructView('bearish')} className={`flex-1 py-2.5 rounded-xl text-xs font-bold transition-all ${structView==='bearish'?'bg-red-500 text-white':'glass text-gray-400'}`}>&darr; Bearish (LH + LL)</button></div><StructureChart prices={structView==='bullish'?bullData.prices:bearData.prices} swings={structView==='bullish'?bullData.swings:bearData.swings} height={300} /><div className="mt-4 grid grid-cols-2 gap-3"><div className="p-3 rounded-xl glass-card" style={{borderLeft:'3px solid #22c55e'}}><h4 className="font-bold text-green-400 text-xs mb-1">HH &mdash; Higher High</h4><p className="text-[10px] text-gray-400">New peak ABOVE the previous peak. Buyers pushed further.</p></div><div className="p-3 rounded-xl glass-card" style={{borderLeft:'3px solid #0ea5e9'}}><h4 className="font-bold text-primary-400 text-xs mb-1">HL &mdash; Higher Low</h4><p className="text-[10px] text-gray-400">Pullback holds ABOVE the previous low. Buyers defending higher.</p></div><div className="p-3 rounded-xl glass-card" style={{borderLeft:'3px solid #f59e0b'}}><h4 className="font-bold text-amber-400 text-xs mb-1">LH &mdash; Lower High</h4><p className="text-[10px] text-gray-400">Rally fails BELOW the previous high. Sellers getting stronger.</p></div><div className="p-3 rounded-xl glass-card" style={{borderLeft:'3px solid #ef4444'}}><h4 className="font-bold text-red-400 text-xs mb-1">LL &mdash; Lower Low</h4><p className="text-[10px] text-gray-400">New trough BELOW the previous trough. Sellers pushed further.</p></div></div><div className="mt-4 p-4 rounded-xl bg-primary-500/5 border border-primary-500/15"><p className="text-sm text-gray-300 leading-relaxed">&#128161; <strong className="text-primary-400">The staircase rule:</strong> Bullish = staircase going UP. Bearish = staircase going DOWN. If the steps stop going in one direction, the staircase is breaking.</p></div></motion.div></section>

<section className="px-5 py-12 max-w-2xl mx-auto"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">02 &mdash; The Three Structure Events</p><h2 className="text-2xl font-extrabold mb-4">BOS &rarr; CHoCH &rarr; MSS</h2><p className="text-sm text-gray-400 mb-6 leading-relaxed">Three events that tell you everything about a trend&apos;s health.</p><div className="space-y-3 mb-6">{demoSteps.map((step,i)=>(<motion.div key={i} initial={{opacity:0,x:-15}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*0.08}} className={`p-4 rounded-xl glass-card cursor-pointer transition-all ${bosStep===i?'ring-1 ring-amber-500/30':''}`} onClick={()=>setBosStep(i)} style={{borderLeftWidth:'3px',borderLeftColor:i===0?'#6b7280':i===1?'#22c55e':i===2?'#0ea5e9':i===3?'#f59e0b':'#ef4444'}}><div className="flex items-center justify-between mb-1"><h3 className="font-bold text-white text-sm">{step.title}</h3>{i<=2&&<span className="text-[10px] px-2 py-0.5 rounded bg-green-500/10 text-green-400 font-bold">BULLISH</span>}{i===3&&<span className="text-[10px] px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 font-bold">WARNING</span>}{i===4&&<span className="text-[10px] px-2 py-0.5 rounded bg-red-500/10 text-red-400 font-bold">REVERSAL</span>}</div><p className="text-xs text-gray-400 leading-relaxed">{step.desc}</p></motion.div>))}</div>
<div className="p-5 rounded-2xl glass-card"><h3 className="font-bold text-amber-400 text-sm mb-4">&#128214; The Three Terms &mdash; Memorise These</h3><div className="space-y-3"><div className="p-3 rounded-xl bg-green-500/5 border border-green-500/15"><h4 className="font-bold text-green-400 text-sm mb-1">BOS &mdash; Break of Structure</h4><p className="text-xs text-gray-400 leading-relaxed">Price breaks past a previous swing point <strong className="text-white">IN the direction of the trend</strong>. BOS = &quot;trend confirmed, keep going.&quot;</p></div><div className="p-3 rounded-xl bg-amber-500/5 border border-amber-500/15"><h4 className="font-bold text-amber-400 text-sm mb-1">CHoCH &mdash; Change of Character</h4><p className="text-xs text-gray-400 leading-relaxed">The FIRST break of structure <strong className="text-white">AGAINST the current trend</strong>. CHoCH = &quot;warning &mdash; something has changed.&quot;</p></div><div className="p-3 rounded-xl bg-red-500/5 border border-red-500/15"><h4 className="font-bold text-red-400 text-sm mb-1">MSS &mdash; Market Structure Shift</h4><p className="text-xs text-gray-400 leading-relaxed">The full reversal: after CHoCH, price establishes structure in the <strong className="text-white">OPPOSITE direction</strong>. MSS = &quot;old trend dead, new trend confirmed.&quot;</p></div></div></div></motion.div></section>

<section className="px-5 py-12 max-w-2xl mx-auto"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">03 &mdash; Fractal Structure</p><h2 className="text-2xl font-extrabold mb-4">Structure Within Structure</h2><div className="p-5 rounded-2xl glass-card mb-6"><p className="text-sm text-gray-400 leading-relaxed mb-4">&#128161; <strong className="text-white">Markets are fractal.</strong> Like Russian nesting dolls, structure exists INSIDE structure. The Daily chart shows a bullish leg. Zoom into that single leg on the 1H chart and you&apos;ll see its OWN set of HH/HL swing points.</p><div className="grid grid-cols-2 gap-3"><div className="p-3 rounded-xl bg-primary-500/5 border border-primary-500/15"><h4 className="font-bold text-primary-400 text-xs mb-1">External Structure (HTF)</h4><p className="text-[10px] text-gray-400">The big-picture swings on Daily/4H. These define the TREND direction.</p></div><div className="p-3 rounded-xl bg-accent-500/5 border border-accent-500/15"><h4 className="font-bold text-accent-400 text-xs mb-1">Internal Structure (LTF)</h4><p className="text-[10px] text-gray-400">Smaller swings on 1H/15M within each external leg. These help TIME your entry.</p></div></div></div><div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/15"><p className="text-sm text-gray-300 leading-relaxed">&#127919; <strong className="text-amber-400">The pro technique:</strong> Use external structure (Daily) for bias. Use internal structure (1H/15M) for entry. When LTF shows CHoCH in the DIRECTION of HTF trend, you have a high-probability entry.</p></div></motion.div></section>

<section className="px-5 py-12 max-w-2xl mx-auto"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">04 &mdash; Read the Structure</p><h2 className="text-2xl font-extrabold mb-2">What Just Happened?</h2><p className="text-sm text-gray-400 mb-6">5 charts. Identify the structure event.</p>
{!gameComplete?(<div><div className="flex items-center justify-between mb-3"><span className="text-xs text-gray-500">Round {gameRound+1} of 5</span><span className="text-xs text-amber-400 font-bold">{gameScore}/{gameRound+(gameAnswers[gameRound]!==null?1:0)} correct</span></div><div className="w-full h-1.5 bg-gray-800 rounded-full mb-4 overflow-hidden"><div className="h-full bg-gradient-to-r from-amber-500 to-accent-500 transition-all" style={{width:`${((gameRound+(gameAnswers[gameRound]!==null?1:0))/5)*100}%`}} /></div><StructureChart prices={gamePrices[gameRound]} height={260} showLabels={false} /><div className="mt-4 space-y-2">{gameOptions.map((opt,oi)=>{const answered=gameAnswers[gameRound]!==null;const isCorrect=oi===gameCorrectIdx[gameRound];const isChosen=gameAnswers[gameRound]===oi;let cls='glass text-gray-300 hover:bg-white/5';if(answered){if(isCorrect)cls='bg-green-500/15 border-green-500/30 text-green-400';else if(isChosen)cls='bg-red-500/15 border-red-500/30 text-red-400';else cls='glass text-gray-600';}return(<button key={oi} onClick={()=>answerGame(oi)} disabled={answered} className={`w-full text-left p-3 rounded-xl border text-sm font-medium transition-all ${cls}`}>{opt} {answered&&isCorrect&&'\u2713'} {answered&&isChosen&&!isCorrect&&'\u2717'}</button>);})}</div><AnimatePresence>{gameAnswers[gameRound]!==null&&(<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0}} className="mt-4"><div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/15"><p className="text-sm text-gray-300 leading-relaxed"><strong className="text-amber-400">Explanation:</strong> {gameExplanations[gameRound]}</p></div>{gameShowNext&&(<button onClick={nextRound} className="mt-3 w-full py-3 rounded-xl bg-gradient-to-r from-amber-500 to-accent-500 text-white text-sm font-bold shadow-lg shadow-amber-500/20 active:scale-95 transition-all">{gameRound<4?'Next Round \u2192':'See Results \u2192'}</button>)}</motion.div>)}</AnimatePresence></div>):(<motion.div initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} className="text-center p-8 glass-card rounded-2xl"><p className={`text-5xl font-extrabold mb-2 ${gameScore>=3?'text-amber-400':'text-red-400'}`}>{gameScore}/5</p><p className="text-sm text-gray-400 mb-4">{gameScore===5?'\uD83C\uDFC6 You read structure like an institution.':gameScore>=3?'Structure is becoming second nature.':'Review BOS vs CHoCH vs MSS carefully.'}</p><button onClick={resetGame} className="px-6 py-2.5 rounded-xl glass text-xs text-gray-300 font-medium hover:text-white transition">Try Again</button></motion.div>)}</motion.div></section>

<section className="px-5 py-12 max-w-2xl mx-auto"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">05 &mdash; Knowledge Check</p><h2 className="text-2xl font-extrabold mb-6">Market Structure Quiz</h2></motion.div><div className="space-y-6">{quizQuestions.map((q,qi)=>(<motion.div key={qi} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="p-5 rounded-2xl glass-card"><p className="text-sm font-bold text-white mb-3">{qi+1}. {q.q}</p><div className="space-y-2">{q.opts.map((opt,oi)=>{const answered=quizAnswers[qi]!==null;const isCorrect=oi===q.a;const isChosen=quizAnswers[qi]===oi;let cls='glass text-gray-300 hover:bg-white/5';if(answered){if(isCorrect)cls='bg-green-500/15 border-green-500/30 text-green-400';else if(isChosen)cls='bg-red-500/15 border-red-500/30 text-red-400';else cls='glass text-gray-600';}return(<button key={oi} onClick={()=>{if(!answered){const na=[...quizAnswers];na[qi]=oi;setQuizAnswers(na);}}} disabled={answered} className={`w-full text-left p-3 rounded-xl border text-sm transition-all ${cls}`}>{opt} {answered&&isCorrect&&'\u2713'} {answered&&isChosen&&!isCorrect&&'\u2717'}</button>);})}</div>{quizAnswers[qi]!==null&&(<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} className="mt-3 p-3 rounded-xl bg-amber-500/5 border border-amber-500/15 text-sm text-gray-400 leading-relaxed"><span className="text-amber-400 font-bold">&check;</span> {q.explain}</motion.div>)}</motion.div>))}</div>{quizDone&&(<motion.div initial={{opacity:0,scale:0.9}} animate={{opacity:1,scale:1}} className="mt-8 text-center p-8 glass-card rounded-2xl"><p className={`text-5xl font-extrabold mb-2 ${score>=66?'text-amber-400':'text-red-400'}`}>{score}%</p><p className="text-sm text-gray-400">{score===100?'\uD83C\uDFC6 Perfect \u2014 structure is your foundation.':score>=66?'Solid structural understanding.':'Review the three structure events.'}</p></motion.div>)}</section>

<section className="px-5 py-16 text-center">{!certUnlocked?(<div className="max-w-md mx-auto p-8 glass rounded-2xl"><p className="text-4xl mb-3 opacity-30">&#128274;</p><p className="text-sm text-gray-500">Score 66%+ to unlock your <strong className="text-amber-400">Pro Certificate</strong></p></div>):(<motion.div initial={{opacity:0,scale:0.85}} animate={{opacity:1,scale:1}} transition={{duration:0.8,type:'spring'}} className="max-w-md mx-auto p-10 rounded-3xl relative overflow-hidden border border-amber-500/20" style={{background:'linear-gradient(145deg, rgba(13,19,32,1), rgba(20,28,46,1))'}}><div className="absolute inset-0 bg-[conic-gradient(from_0deg,transparent,rgba(239,68,68,0.06),transparent,rgba(245,158,11,0.04),transparent)] animate-spin" style={{animationDuration:'12s'}} /><div className="absolute inset-[1px] rounded-3xl border border-amber-500/10" /><div className="relative z-10"><div className="w-[80px] h-[80px] mx-auto mb-5 rounded-full bg-gradient-to-br from-red-500 to-amber-500 flex items-center justify-center text-4xl shadow-lg shadow-red-500/30">&#127959;&#65039;</div><p className="text-[10px] font-semibold text-amber-400 uppercase tracking-widest mb-2">Pro Certificate</p><h3 className="text-xl font-extrabold mb-1">Certificate of Mastery</h3><p className="text-sm text-gray-400 mb-5 leading-relaxed">Has mastered<br /><strong className="text-white">Level 3.2: Market Structure Mastery</strong><br />at ATLAS Academy by Interakktive</p><p className="bg-gradient-to-r from-red-400 via-amber-400 to-primary-400 bg-clip-text text-transparent font-bold text-lg mb-1" style={{WebkitTransform:'translateZ(0)'}}>&#8212; Structure Analyst &#8212;</p><p className="font-mono text-[11px] text-gray-500 mb-4">{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</p><p className="font-mono text-[9px] text-amber-600/60 tracking-wider uppercase">PRO-CERT-L3.2-{Math.random().toString(36).substring(2,10).toUpperCase()}</p></div></motion.div>)}</section>

<section className="text-center px-5 pt-10 pb-24"><p className="text-xs tracking-widest uppercase text-gray-600 mb-4">Up Next</p><h2 className="text-xl font-bold mb-6">Lesson 3.3 &mdash; Liquidity: The #1 Concept</h2><Link href="/academy" className="inline-flex items-center gap-2.5 px-8 py-4 rounded-xl bg-gradient-to-r from-amber-500 to-accent-500 hover:from-amber-600 hover:to-accent-600 text-white font-bold text-sm shadow-lg shadow-amber-500/20 transition-all active:scale-95">Continue <ArrowRight className="w-4 h-4" /></Link></section>
</div>);}
