// app/academy/lesson/trade-autopsy/page.tsx
// ATLAS Academy — Lesson 7.10: The Trade Autopsy [PRO]
// Gold/amber PRO styling — Crown badge — PRO · LEVEL 7
// GROUNDBREAKING: 7-Step Trade Autopsy Tool — forensic diagnostic with A-F grading
// TEMPLATE: Matches Level 6 Lesson 8 (trade-management) gold standard exactly
'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import { Crown, ChevronDown } from 'lucide-react';

const fadeUp = { hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.5 } } };

function Confetti({ active }: { active: boolean }) {
  if (!active) return null;
  return (<div className="fixed inset-0 pointer-events-none z-50">{Array.from({ length: 60 }).map((_, i) => (<motion.div key={i} initial={{ y: -20, x: Math.random() * (typeof window !== 'undefined' ? window.innerWidth : 400), opacity: 1 }} animate={{ y: (typeof window !== 'undefined' ? window.innerHeight : 800) + 20, rotate: Math.random() * 720, opacity: 0 }} transition={{ duration: 2 + Math.random() * 2, delay: Math.random() * 0.5 }} className="absolute w-2 h-2 rounded-sm" style={{ background: ['#f59e0b', '#d946ef', '#34d399', '#3b82f6', '#ef4444'][i % 5] }} />))}</div>);
}

function AnimScene({ drawFn, height = 300 }: { drawFn: (ctx: CanvasRenderingContext2D, w: number, h: number, f: number) => void; height?: number }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const frameRef = useRef(0); const animRef = useRef(0);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); if (!ctx) return; const dpr = window.devicePixelRatio || 1; const rect = canvas.getBoundingClientRect(); canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; ctx.scale(dpr, dpr); const loop = () => { ctx.clearRect(0, 0, rect.width, rect.height); drawFn(ctx, rect.width, rect.height, frameRef.current); frameRef.current++; animRef.current = requestAnimationFrame(loop); }; loop(); return () => cancelAnimationFrame(animRef.current); }, [drawFn, height]);
  return <div className="w-full rounded-2xl overflow-hidden bg-black/30 border border-white/5"><canvas ref={canvasRef} style={{ width: '100%', height }} /></div>;
}

// ============================================================
// ANIMATION 1: Autopsy Pipeline — 7 connected nodes
// ============================================================
function AutopsyPipelineAnimation() {
  const draw = useCallback((ctx: CanvasRenderingContext2D, w: number, h: number, f: number) => {
    const t = f * 0.004; const cx = w / 2;
    ctx.fillStyle = 'rgba(255,255,255,0.5)'; ctx.font = 'bold 11px system-ui'; ctx.textAlign = 'center'; ctx.fillText('The 7-Step Trade Autopsy', cx, 16);
    const steps = [{ label: 'HTF BIAS', icon: '🧭', color: '#3b82f6' }, { label: 'SETUP', icon: '🎯', color: '#8b5cf6' }, { label: 'TRIGGER', icon: '⚡', color: '#f59e0b' }, { label: 'STOP', icon: '🛡️', color: '#ef4444' }, { label: 'MANAGE', icon: '♟️', color: '#26A69A' }, { label: 'EMOTION', icon: '🧠', color: '#ec4899' }, { label: 'LESSON', icon: '💡', color: '#f59e0b' }];
    const cycle = (t % 12); const activeIdx = Math.min(6, Math.floor(cycle * 0.7));
    const pad = 20; const availW = w - pad * 2; const stepW = availW / 7; const midY = h / 2 + 5; const nodeR = Math.min(18, stepW * 0.32);
    for (let i = 0; i < 6; i++) { const x1 = pad + (i + 0.5) * stepW + nodeR; const x2 = pad + (i + 1.5) * stepW - nodeR; const lit = i < activeIdx; ctx.strokeStyle = lit ? steps[i].color + '60' : 'rgba(255,255,255,0.06)'; ctx.lineWidth = lit ? 2 : 1; ctx.setLineDash(lit ? [] : [3, 3]); ctx.beginPath(); ctx.moveTo(x1, midY); ctx.lineTo(x2, midY); ctx.stroke(); ctx.setLineDash([]); if (i === activeIdx - 1 && lit) { const pulseX = x1 + (x2 - x1) * ((t * 2) % 1); ctx.beginPath(); ctx.arc(pulseX, midY, 3, 0, Math.PI * 2); ctx.fillStyle = steps[i].color + '80'; ctx.fill(); } }
    steps.forEach((s, i) => { const x = pad + (i + 0.5) * stepW; const isActive = i <= activeIdx; const isCurrent = i === activeIdx; const pulse = isCurrent ? Math.sin(t * 4) * 0.15 + 0.85 : 1; if (isCurrent) { ctx.beginPath(); ctx.arc(x, midY, nodeR + 6, 0, Math.PI * 2); ctx.fillStyle = s.color + '15'; ctx.fill(); } ctx.beginPath(); ctx.arc(x, midY, nodeR * pulse, 0, Math.PI * 2); ctx.fillStyle = isActive ? s.color + '20' : 'rgba(255,255,255,0.02)'; ctx.fill(); ctx.strokeStyle = isActive ? s.color + '80' : 'rgba(255,255,255,0.08)'; ctx.lineWidth = isCurrent ? 2 : 1; ctx.stroke(); ctx.font = `${isActive ? 14 : 11}px system-ui`; ctx.textAlign = 'center'; ctx.fillText(s.icon, x, midY + 5); ctx.fillStyle = isActive ? s.color : 'rgba(255,255,255,0.15)'; ctx.font = `${isCurrent ? 'bold ' : ''}${isActive ? 8 : 7}px system-ui`; ctx.fillText(s.label, x, midY + nodeR + 16); ctx.fillStyle = isActive ? 'rgba(255,255,255,0.4)' : 'rgba(255,255,255,0.08)'; ctx.font = '7px system-ui'; ctx.fillText(`Step ${i + 1}`, x, midY - nodeR - 8); });
    if (activeIdx >= 6 && cycle > 9) { const gradeAlpha = Math.min(1, (cycle - 9) * 0.5); ctx.fillStyle = `rgba(245,158,11,${gradeAlpha})`; ctx.font = 'bold 12px system-ui'; ctx.textAlign = 'center'; ctx.fillText('→ TRADE GRADE: B+ (Setup & Trigger strong, Management weak)', cx, h - 14); }
  }, []);
  return <AnimScene drawFn={draw} height={260} />;
}

// ============================================================
// ANIMATION 2: Failure Heatmap
// ============================================================
function FailureHeatmapAnimation() {
  const draw = useCallback((ctx: CanvasRenderingContext2D, w: number, h: number, f: number) => {
    const t = f * 0.005;
    ctx.fillStyle = 'rgba(255,255,255,0.5)'; ctx.font = 'bold 11px system-ui'; ctx.textAlign = 'center'; ctx.fillText('Where 500 Losing Trades Actually Failed', w / 2, 16);
    const steps = [{ label: 'HTF Bias', failPct: 18, color: '#3b82f6' }, { label: 'Setup', failPct: 12, color: '#8b5cf6' }, { label: 'Trigger', failPct: 15, color: '#f59e0b' }, { label: 'Stop', failPct: 22, color: '#ef4444' }, { label: 'Management', failPct: 25, color: '#26A69A' }, { label: 'Emotion', failPct: 35, color: '#ec4899' }, { label: 'Lesson', failPct: 8, color: '#f59e0b' }];
    const pad = 30; const barAreaL = pad + 70; const barAreaR = w - pad; const barMaxW = barAreaR - barAreaL; const barH = 22; const gap = 8; const startY = 40; const animProgress = Math.min(1, (t % 6) / 3);
    steps.forEach((s, i) => { const y = startY + i * (barH + gap); const barW = Math.max(0, (s.failPct / 40) * barMaxW * Math.min(1, animProgress * 2 - i * 0.15)); ctx.fillStyle = 'rgba(255,255,255,0.5)'; ctx.font = '9px system-ui'; ctx.textAlign = 'right'; ctx.fillText(s.label, barAreaL - 8, y + barH / 2 + 3); ctx.fillStyle = 'rgba(255,255,255,0.02)'; ctx.beginPath(); ctx.roundRect(barAreaL, y, barMaxW, barH, 4); ctx.fill(); if (barW > 0) { const hi = s.failPct / 35; ctx.fillStyle = `rgba(${Math.round(239 * hi + 59 * (1 - hi))},${Math.round(83 * hi + 130 * (1 - hi))},${Math.round(80 * hi + 246 * (1 - hi))},0.6)`; ctx.beginPath(); ctx.roundRect(barAreaL, y, barW, barH, 4); ctx.fill(); if (animProgress > 0.5) { ctx.fillStyle = 'rgba(255,255,255,0.8)'; ctx.font = 'bold 9px system-ui'; ctx.textAlign = 'left'; ctx.fillText(`${s.failPct}%`, barAreaL + barW + 6, y + barH / 2 + 3); } } });
    if (animProgress > 0.8) { ctx.fillStyle = 'rgba(236,72,153,0.7)'; ctx.font = 'bold 9px system-ui'; ctx.textAlign = 'center'; ctx.fillText('→ EMOTION is the #1 failure point — not strategy, not analysis.', w / 2, h - 12); }
  }, []);
  return <AnimScene drawFn={draw} height={290} />;
}

// ============================================================
// 7-STEP AUTOPSY TOOL DATA
// ============================================================
const autopsySteps = [
  { id: 1, title: 'HTF Bias', icon: '🧭', color: '#3b82f6', question: 'Was your higher-timeframe bias correct?', options: [{ value: 'correct', label: 'Yes — Daily/4H direction was right', score: 3 }, { value: 'partially', label: 'Partially — direction right but timing off', score: 2 }, { value: 'wrong', label: 'No — traded against the HTF trend', score: 0 }, { value: 'none', label: 'I didn\'t check the HTF bias', score: 0 }], followUp: 'What was the HTF showing?', insight: 'HTF bias errors are STRATEGIC failures. If the compass is wrong, perfect execution still loses.' },
  { id: 2, title: 'Setup Criteria', icon: '🎯', color: '#8b5cf6', question: 'Did the setup meet ALL your checklist criteria?', options: [{ value: 'all', label: 'Yes — every criterion was met', score: 3 }, { value: 'most', label: 'Most — 1-2 criteria marginal', score: 2 }, { value: 'few', label: 'Only some — I forced the trade', score: 1 }, { value: 'none', label: 'No checklist — traded on instinct', score: 0 }], followUp: 'Which criteria were met/missing?', insight: 'Setup errors are SELECTION failures. A perfect trigger on a flawed setup is B-grade at best.' },
  { id: 3, title: 'Trigger Quality', icon: '⚡', color: '#f59e0b', question: 'How clean was the entry trigger?', options: [{ value: 'textbook', label: 'Textbook — clear candle confirmation', score: 3 }, { value: 'decent', label: 'Decent — slightly off-level', score: 2 }, { value: 'weak', label: 'Weak — entered before trigger formed', score: 1 }, { value: 'none', label: 'No trigger — chased price', score: 0 }], followUp: 'What did you see at the moment of entry?', insight: 'Trigger errors are TIMING failures. A-grade setups with C-grade triggers produce C-grade results.' },
  { id: 4, title: 'Stop Placement', icon: '🛡️', color: '#ef4444', question: 'Was the stop placed correctly?', options: [{ value: 'structural', label: 'Yes — behind structure', score: 3 }, { value: 'acceptable', label: 'Acceptable — slightly tight', score: 2 }, { value: 'arbitrary', label: 'Arbitrary — pip count, not structure', score: 1 }, { value: 'none', label: 'No stop loss placed', score: 0 }], followUp: 'Where was the stop relative to structure?', insight: 'Stop errors are RISK MANAGEMENT failures. Arbitrary stops get hunted. Structural stops survive.' },
  { id: 5, title: 'Trade Management', icon: '♟️', color: '#26A69A', question: 'Did you follow your management plan?', options: [{ value: 'perfectly', label: 'Yes — followed exactly', score: 3 }, { value: 'mostly', label: 'Mostly — one deviation', score: 2 }, { value: 'poorly', label: 'Poorly — multiple deviations', score: 1 }, { value: 'none', label: 'No plan — managed on feel', score: 0 }], followUp: 'What deviations occurred?', insight: 'Management errors are EXECUTION failures. The plan was sound, but you interfered.' },
  { id: 6, title: 'Emotional State', icon: '🧠', color: '#ec4899', question: 'What was your emotional state?', options: [{ value: 'calm', label: 'Calm and detached', score: 3 }, { value: 'anxious', label: 'Anxious but controlled', score: 2 }, { value: 'reactive', label: 'Reactive — fear/greed influenced', score: 1 }, { value: 'tilted', label: 'Tilted — revenge or FOMO', score: 0 }], followUp: 'What emotion was strongest?', insight: 'Emotional errors are PSYCHOLOGICAL failures. If tilted, the entire trade was compromised.' },
  { id: 7, title: 'Key Lesson', icon: '💡', color: '#f59e0b', question: 'Can you identify ONE specific, actionable lesson?', options: [{ value: 'specific', label: 'Yes — I know exactly what to change', score: 3 }, { value: 'general', label: 'Somewhat — general idea', score: 2 }, { value: 'vague', label: 'Vague — "be more disciplined"', score: 1 }, { value: 'nothing', label: 'Nothing — don\'t see what went wrong', score: 0 }], followUp: 'Write the ONE lesson in one sentence.', insight: '"Be more disciplined" is not a lesson. "Wait for the 15M close before entering" IS a lesson.' },
];

const lessonTiers = [
  { tier: 'F-TIER', example: '"I need to be more disciplined"', problem: 'Not actionable. You will write this same lesson next week.', color: '#ef4444' },
  { tier: 'D-TIER', example: '"My entry was bad"', problem: 'No root cause. WHAT was bad about it?', color: '#f97316' },
  { tier: 'C-TIER', example: '"I entered too late and R:R degraded"', problem: 'Identifies the WHAT but not the HOW TO FIX.', color: '#FFB300' },
  { tier: 'B-TIER', example: '"Next time, limit order at OB level instead of market order"', problem: 'Specific and actionable, but no measurement criteria.', color: '#3b82f6' },
  { tier: 'A-TIER', example: '"For 20 trades: limit orders at OB levels only. Track fill rate vs market orders."', problem: 'Specific action + sample size + measurement. THIS changes behaviour.', color: '#26A69A' },
];

const autopsyMistakes = [
  { title: 'Outcome Bias', mistake: 'Grading based on whether it won or lost. A winning revenge trade gets an A because "it worked."', fix: 'Grade PROCESS, not OUTCOME. "Would I take this exact trade 100 times?"' },
  { title: 'Hindsight Editing', mistake: 'After seeing the outcome, rewriting reasoning to sound prescient.', fix: 'Write autopsy notes BEFORE looking at what price did after exit.' },
  { title: 'Skipping Step 6', mistake: 'Admitting "I was tilted" feels uncomfortable. So traders skip it or lie.', fix: 'Step 6 is the most important step. The data shows emotion is the #1 failure point.' },
  { title: 'Only Autopsying Losers', mistake: 'Skipping winners creates survivorship bias. You never discover winning F-grade habits.', fix: 'Autopsy best win AND worst loss each week. Winning F-grades are ticking time bombs.' },
];

const quizQuestions = [
  { q: 'The primary purpose of a trade autopsy is:', opts: ['Determine if the trade was profitable', 'Identify WHERE in the process the failure occurred', 'Confirm your strategy is correct', 'Calculate your win rate'], correct: 1, explain: 'A trade autopsy isolates the SPECIFIC step where the process broke down — not whether you made or lost money. The location of failure determines the fix.' },
  { q: 'A trade had correct bias, perfect setup, clean trigger, but was closed early due to fear. The failure is at:', opts: ['Step 1: HTF Bias', 'Step 3: Trigger Quality', 'Step 5: Trade Management', 'Step 6: Emotional State'], correct: 3, explain: 'Steps 1-4 scored 3/3. The plan, setup, and trigger were all correct. The failure was purely psychological — fear caused the premature exit. Emotion is the root cause; management is the symptom.' },
  { q: 'Your autopsy reveals: correct bias, partial setup, decent trigger, structural stop, perfect management, calm. The grade is likely:', opts: ['A — mostly correct', 'B — the missing criterion in Step 2 caps the grade', 'F — any flaw means failure', 'D — partial setup invalidates everything'], correct: 1, explain: 'Most steps scored well. The partial setup (Step 2 scoring 2/3) is the weakest link but does not invalidate the trade. This is a B-grade execution with one area for improvement.' },
  { q: '"I need to be more patient" as a trade autopsy lesson is:', opts: ['Excellent — patience is key', 'Acceptable — captures the essence', 'Too vague — "wait for 15M close" is required', 'Irrelevant'], correct: 2, explain: '"Be more patient" is an F-tier lesson — not actionable, not measurable. A specific action like "wait for 15M candle close before entering" can be tracked and practiced.' },
  { q: 'A winning trade should be autopsied because:', opts: ['Winners don\'t need analysis', 'A win with process errors creates dangerous false confidence', 'Only losers have lessons', 'To celebrate'], correct: 1, explain: 'A winning F-grade trade reinforces bad behaviour. Your brain encodes "breaking rules works." The next time you are tempted, the memory of this win pushes you toward violation.' },
  { q: 'The failure heatmap shows the #1 failure point across 500 losing trades is:', opts: ['HTF Bias', 'Trigger Quality', 'Emotional State', 'Stop Placement'], correct: 2, explain: 'Emotion (35%) is the leading cause of trade failure — not strategy or analysis. Most traders blame their strategy when the data says blame psychology and execution.' },
  { q: 'If Step 4 (Stop Placement) scores 0/3 ("no stop placed"), the overall grade should be:', opts: ['Whatever the other steps average', 'F — no stop loss is automatic F regardless', 'D — bad but other steps compensate', 'Depends on outcome'], correct: 1, explain: 'No stop loss is a non-negotiable automatic F. A trade without a stop is not a trade — it is gambling. Fix this before analysing anything else.' },
  { q: 'The correct cadence for trade autopsies is:', opts: ['Only on losing trades', 'Only biggest winners and losers', 'Every trade for the first 100, then weekly on key trades', 'Once a month'], correct: 2, explain: 'Every trade for the first 100 builds the habit and data foundation. After 100, autopsy your best win, worst loss, and any rule-break each week.' },
];

const gameRounds = [
  { scenario: '<strong>Autopsy Case 1:</strong> Long XAUUSD. Daily bullish ✓. 15M BOS + OB pullback ✓. Bullish engulfing trigger ✓. Stop 2 pips below OB ✓. Price moved to +0.8R, pulled back to &minus;0.2R. You panicked and closed at &minus;0.2R. Price then ran to +2.3R. Where did this trade fail?', options: [
    { text: 'Step 3: Trigger — entry was poorly timed', correct: false, explain: 'Trigger was textbook — bullish engulfing at OB. 3/3. The trade actually WORKED. The failure was later.' },
    { text: 'Step 5: Management — closing at &minus;0.2R broke the plan', correct: false, explain: 'Close — management WAS violated. But the REASON was emotional. Management is the symptom. Emotion is the disease.' },
    { text: 'Step 6: Emotion — panic caused the early close. Steps 1-4 were all correct.', correct: true, explain: 'Steps 1-4 all scored 3/3. The failure was purely psychological — fear of giving back +0.8R. An A-grade setup with an F-grade emotional response. Grade: C.' },
  ]},
  { scenario: '<strong>Autopsy Case 2:</strong> Short EUR/USD during NY. Daily was RANGING (no clear bias). 4H broke structure bearish. 15M FVG entry. Stop above swing high. Trade hit SL. On review, Daily ranging = no directional conviction.', options: [
    { text: 'Step 1: HTF Bias — Daily ranging = no trade. Foundation was flawed.', correct: true, explain: 'When Daily is ranging, there IS no HTF bias. A 4H break during a Daily range lacks HTF backing. Steps 2-5 were arguably fine, but built on a flawed foundation. Grade: D.' },
    { text: 'Step 2: Setup — FVG wasn\'t clean enough', correct: false, explain: 'FVG was valid on 15M. The setup was fine IN ISOLATION. Root cause is Step 1.' },
    { text: 'Step 4: Stop — should have been wider', correct: false, explain: 'Stop was structurally correct. Wider stop = bigger loss. The problem was taking the trade at all.' },
  ]},
  { scenario: '<strong>Autopsy Case 3:</strong> Long GBP/USD. Daily bullish ✓. 4H demand OB ✓. 15M pulled back to OB. You entered BEFORE the trigger candle closed — a doji was forming, you assumed bullish. It closed bearish. Price swept below OB, hit your stop, then reversed to TP.', options: [
    { text: 'Step 2: Setup — OB was invalid', correct: false, explain: 'OB was valid — price respected it and trade WOULD have worked. Setup was fine.' },
    { text: 'Step 3: Trigger — entering before candle closed. A doji is NOT a trigger.', correct: true, explain: 'Bias ✓, Setup ✓, but TRIGGER was jumped. A forming doji is not a confirmed trigger. Wait for the close. Always. Grade: C+.' },
    { text: 'Step 4: Stop — too tight if it got swept', correct: false, explain: 'Stop below OB is structurally correct. The sweep happened because entry was premature.' },
  ]},
  { scenario: '<strong>Autopsy Case 4:</strong> 3 losses into the day. Playbook says max 2 trades. You see a "perfect" NASDAQ setup. Enter with 2% risk (normal is 1%). Trade wins +2R. You feel vindicated. Grade this trade.', options: [
    { text: 'A — correct and profitable. Recovery trade worked.', correct: false, explain: 'Profitability does NOT determine grade. Two rule breaks: trade limit exceeded AND risk doubled. A winning rule-break is MORE dangerous than a losing one.' },
    { text: 'F — two rule breaks (max trades AND doubled risk). Win is irrelevant.', correct: true, explain: 'F-grade regardless of outcome. Max trades exceeded + 2&times; risk = process violation. If this trade had lost: &minus;4% day instead of &minus;2%. The win is a statistical accident. Grade: F.' },
    { text: 'B — setup was valid even if rules were bent', correct: false, explain: 'Two deviations, not one. "Bending" rules after 3 losses is textbook revenge trading.' },
  ]},
  { scenario: '<strong>Autopsy Case 5:</strong> Full 7-step autopsy complete. Your lesson is: "I need to be more disciplined and follow my rules better." Your mentor asks you to rewrite it.', options: [
    { text: '"I will only enter after the 15M candle closes, because in this trade I entered 3 candles early and got stopped before the move."', correct: true, explain: 'SPECIFIC, ACTIONABLE. Identifies: what happened (entered 3 candles early), why it mattered (got stopped), the fix (wait for 15M close). Measurable. Practicable.' },
    { text: '"I need to improve my psychology and control my emotions better."', correct: false, explain: 'Same vague lesson in different words. How do you "improve psychology"? By doing what, specifically?' },
    { text: '"I should have taken the opposite direction based on the higher timeframe."', correct: false, explain: 'Hindsight observation, not a process lesson. You cannot apply "take the opposite direction" to future trades.' },
  ]},
];

// ============================================================
// MAIN COMPONENT
// ============================================================
export default function TradeAutopsyPage() {
  const [scrollY, setScrollY] = useState(0);
  useEffect(() => { const h = () => setScrollY(window.scrollY); window.addEventListener('scroll', h, { passive: true }); return () => window.removeEventListener('scroll', h); }, []);
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({});
  const toggle = (id: string) => setOpenSections(p => ({ ...p, [id]: !p[id] }));

  // Autopsy Tool
  const [autopsyStep, setAutopsyStep] = useState(0);
  const [autopsyAnswers, setAutopsyAnswers] = useState<(string | null)[]>(autopsySteps.map(() => null));
  const [autopsyNotes, setAutopsyNotes] = useState<string[]>(autopsySteps.map(() => ''));
  const [autopsyComplete, setAutopsyComplete] = useState(false);
  const handleAutopsyAnswer = (value: string) => { const newA = [...autopsyAnswers]; newA[autopsyStep] = value; setAutopsyAnswers(newA); };
  const nextAutopsyStep = () => { if (autopsyStep < autopsySteps.length - 1) setAutopsyStep(s => s + 1); else setAutopsyComplete(true); };
  const getStepScore = (idx: number): number => { const ans = autopsyAnswers[idx]; if (!ans) return 0; const opt = autopsySteps[idx].options.find(o => o.value === ans); return opt ? opt.score : 0; };
  const getAutopsyScore = (): number => autopsyAnswers.reduce<number>((total, ans, i) => { if (!ans) return total; const opt = autopsySteps[i].options.find(o => o.value === ans); return total + (opt ? opt.score : 0); }, 0);
  const getWeakestStep = (): string => { let minScore = 4; let weakest = ''; autopsySteps.forEach((step, i) => { const score = getStepScore(i); if (score < minScore) { minScore = score; weakest = step.title; } }); return weakest; };
  const getAutopsyGrade = (): { grade: string; color: string; label: string; feedback: string } => {
    const score = getAutopsyScore(); const pct = (score / 21) * 100;
    if (autopsyAnswers[3] === 'none') return { grade: 'F', color: '#ef4444', label: 'CRITICAL FAILURE', feedback: 'No stop loss = automatic F. Fix this before anything else.' };
    if (autopsyAnswers[5] === 'tilted') return { grade: 'F', color: '#ef4444', label: 'PSYCHOLOGICAL FAILURE', feedback: 'Trading while tilted invalidates the entire process. Recognise tilt and walk away.' };
    if (pct >= 90) return { grade: 'A', color: '#26A69A', label: 'ELITE EXECUTION', feedback: 'Near-perfect process. Even if this trade lost, it was a high-quality decision.' };
    if (pct >= 76) return { grade: 'B', color: '#3b82f6', label: 'SOLID PROCESS', feedback: 'Strong execution with minor areas for improvement. Focus on the weakest step.' };
    if (pct >= 57) return { grade: 'C', color: '#FFB300', label: 'DEVELOPING', feedback: 'Multiple process errors. Review steps that scored 1 or below.' };
    if (pct >= 38) return { grade: 'D', color: '#f97316', label: 'SIGNIFICANT ISSUES', feedback: 'Major breakdowns. Revisit your checklist before your next trade.' };
    return { grade: 'F', color: '#ef4444', label: 'PROCESS FAILURE', feedback: 'Fundamental errors. This trade should not have been taken.' };
  };

  // Game
  const [gameRound, setGameRound] = useState(0);
  const [gameAnswers, setGameAnswers] = useState<(number | null)[]>(gameRounds.map(() => null));
  const [gameScore, setGameScore] = useState(0);
  const handleGameAnswer = (optIdx: number) => { if (gameAnswers[gameRound] !== null) return; const newA = [...gameAnswers]; newA[gameRound] = optIdx; setGameAnswers(newA); if (gameRounds[gameRound].options[optIdx].correct) setGameScore(s => s + 1); };

  // Quiz
  const [quizAnswers, setQuizAnswers] = useState<(number | null)[]>(quizQuestions.map(() => null));
  const handleQuizAnswer = (qi: number, oi: number) => { if (quizAnswers[qi] !== null) return; const n = [...quizAnswers]; n[qi] = oi; setQuizAnswers(n); };
  const quizDone = quizAnswers.every(a => a !== null);
  const quizScoreVal = quizDone ? Math.round((quizAnswers.filter((a, i) => a === quizQuestions[i].correct).length / quizQuestions.length) * 100) : 0;
  const certUnlocked = quizDone && quizScoreVal >= 66;
  const [showConfetti, setShowConfetti] = useState(false);
  useEffect(() => { if (certUnlocked) { setShowConfetti(true); const t = setTimeout(() => setShowConfetti(false), 4000); return () => clearTimeout(t); }}, [certUnlocked]);

  return (
    <div className="min-h-screen text-white" style={{ background: 'linear-gradient(to bottom, #060a12, #0a0f1a)' }}>
      <Confetti active={showConfetti} />
      <div className="fixed top-0 left-0 right-0 z-50 h-1 bg-gray-900/50"><motion.div className="h-full bg-gradient-to-r from-amber-500 to-accent-500" style={{ width: `${Math.min((scrollY / (typeof document !== 'undefined' ? document.body.scrollHeight - window.innerHeight : 1)) * 100, 100)}%` }} /></div>
      <nav className="fixed top-1 left-0 right-0 z-40 flex items-center justify-between px-5 py-2.5">
        <Link href="/academy" className="font-extrabold text-sm tracking-wide bg-gradient-to-r from-amber-400 to-accent-400 bg-clip-text text-transparent" style={{ WebkitTransform: 'translateZ(0)' }}>ATLAS ACADEMY</Link>
        <div className="flex items-center gap-2"><Crown className="w-3.5 h-3.5 text-amber-400" /><span className="text-xs font-bold text-amber-400">PRO &middot; LEVEL 7</span></div>
      </nav>

      <section className="relative min-h-[85vh] flex flex-col items-center justify-center text-center px-6 pt-20">
        <div className="absolute top-[-200px] left-1/2 -translate-x-1/2 w-[700px] h-[700px] bg-[radial-gradient(circle,rgba(245,158,11,0.08),transparent_70%)] pointer-events-none" />
        <div className="absolute top-[-50px] right-[20%] w-[500px] h-[500px] bg-[radial-gradient(circle,rgba(217,70,239,0.05),transparent_70%)] pointer-events-none" />
        <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.15 } } }} className="relative z-10">
          <motion.div variants={fadeUp}><p className="text-xs font-semibold tracking-widest uppercase text-amber-400 mb-3">Level 7 &middot; Lesson 10</p></motion.div>
          <motion.h1 variants={fadeUp} className="text-[clamp(32px,7vw,52px)] font-black leading-[1.1] tracking-tight mb-5">The Trade<br /><span className="bg-gradient-to-r from-red-400 via-amber-400 to-purple-400 bg-clip-text text-transparent" style={{ WebkitTransform: 'translateZ(0)' }}>Autopsy</span></motion.h1>
          <motion.p variants={fadeUp} className="text-gray-300 text-lg max-w-lg mx-auto leading-relaxed">Not &ldquo;I lost.&rdquo; But WHERE in the 7-step process the failure occurred — and exactly how to fix it.</motion.p>
          <motion.div variants={fadeUp} className="mt-12 flex flex-col items-center gap-1.5"><span className="text-xs tracking-widest uppercase text-gray-600">Scroll to begin</span><div className="w-5 h-5 border-r-2 border-b-2 border-amber-400 rotate-45 opacity-50 animate-bounce" /></motion.div>
        </motion.div>
      </section>

      {/* S00 */}
      <section className="max-w-2xl mx-auto px-5 py-20"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
        <p className="text-xs font-bold tracking-widest uppercase text-amber-400 mb-6">First &mdash; Why This Matters</p>
        <div className="p-6 rounded-2xl glass-card mb-6">
          <p className="text-xl font-extrabold mb-3">🔍 The Coroner&rsquo;s Report</p>
          <p className="text-gray-400 leading-relaxed mb-4">A coroner doesn&rsquo;t write &ldquo;patient died&rdquo; on the report. They document the <strong className="text-amber-400">exact cause</strong>: which organ, which failure, which chain of events. A trade autopsy works the same way. &ldquo;I lost&rdquo; is useless. &ldquo;I lost because I entered before the 15M trigger closed, which placed my stop 4 pips too high, which meant the Asian sweep caught me before the real move&rdquo; — <strong className="text-white">that</strong> is information you can act on.</p>
        </div>
        <div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/15">
          <p className="text-xs font-bold text-amber-400 mb-2">&#128270; REAL SCENARIO</p>
          <p className="text-sm text-gray-400 leading-relaxed">500 losing trades autopsied using this 7-step framework. Only <strong className="text-white">18% were wrong bias</strong>. Only <strong className="text-white">12% were bad setups</strong>. The #1 failure: <strong className="text-red-400">emotional state (35%)</strong>, followed by <strong className="text-red-400">management (25%)</strong> and <strong className="text-red-400">stop placement (22%)</strong>. Most traders blame strategy. The data says blame psychology.</p>
        </div>
      </motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">01 &mdash; The Diagnostic Pipeline</p><h2 className="text-2xl font-extrabold mb-4">7 Steps, One Diagnosis</h2><p className="text-gray-400 text-sm mb-6">Each step isolates one dimension. The failure point is where the chain breaks.</p><AutopsyPipelineAnimation /></motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">02 &mdash; Where Trades Actually Fail</p><h2 className="text-2xl font-extrabold mb-4">500 Losing Trades Analysed</h2><p className="text-gray-400 text-sm mb-6">Emotion leads. Not strategy, not analysis.</p><FailureHeatmapAnimation /></motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">03 &mdash; The 7 Steps Explained</p><h2 className="text-2xl font-extrabold mb-4">Each Step in Detail</h2><div className="space-y-3">{autopsySteps.map((step, i) => (<div key={step.id}><button onClick={() => toggle(`as-${i}`)} className="w-full text-left p-4 rounded-xl glass hover:bg-white/5 transition-all flex items-center justify-between"><div className="flex items-center gap-2"><span className="text-sm" style={{ background: step.color + '15', padding: '2px 6px', borderRadius: '6px' }}>{step.icon}</span><span className="text-sm font-bold text-gray-200">Step {step.id}: {step.title}</span></div><ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${openSections[`as-${i}`] ? 'rotate-180' : ''}`} /></button><AnimatePresence>{openSections[`as-${i}`] && (<motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="p-4 rounded-b-xl bg-white/[0.02] border-x border-b border-white/[0.05]"><p className="text-sm text-gray-300 mb-2">{step.question}</p><div className="space-y-1 mb-3">{step.options.map(opt => (<div key={opt.value} className="flex items-center gap-2 text-xs text-gray-400"><span className={`w-5 h-5 rounded flex items-center justify-center text-[10px] font-bold ${opt.score === 3 ? 'bg-green-500/20 text-green-400' : opt.score === 2 ? 'bg-amber-500/20 text-amber-400' : opt.score === 1 ? 'bg-orange-500/20 text-orange-400' : 'bg-red-500/20 text-red-400'}`}>{opt.score}</span><span>{opt.label}</span></div>))}</div><p className="text-xs leading-relaxed" style={{ color: step.color }}>{step.insight}</p></div></motion.div>)}</AnimatePresence></div>))}</div></motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">04 &mdash; The Grading System</p><h2 className="text-2xl font-extrabold mb-4">A to F — What Each Grade Means</h2><div className="p-6 rounded-2xl glass-card space-y-3">
        {[{ g: 'A', r: '19-21/21', c: '#26A69A', d: 'Elite. Every step 2+. These trades compound over time.' }, { g: 'B', r: '16-18/21', c: '#3b82f6', d: 'Strong process, 1-2 minor gaps. B-grade traders are consistently profitable.' }, { g: 'C', r: '12-15/21', c: '#FFB300', d: 'Mixed. Some strong, some weak. Focus on the lowest-scoring step.' }, { g: 'D', r: '8-11/21', c: '#f97316', d: 'Major issues. This trade probably shouldn\'t have been taken.' }, { g: 'F', r: '0-7 or auto-fail', c: '#ef4444', d: 'Process failure. Auto-F: no stop loss OR trading tilted.' }].map(item => (
          <div key={item.g} className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"><p className="text-sm"><strong style={{ color: item.c }}>{item.g} ({item.r})</strong> <span className="text-gray-500">=</span> <span className="text-gray-400">{item.d}</span></p></div>
        ))}
      </div></motion.div></section>

      {/* S05 — GROUNDBREAKING: 7-Step Trade Autopsy Tool */}
      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">05 &mdash; Interactive Challenge</p><h2 className="text-2xl font-extrabold mb-2">7-Step Trade Autopsy Tool</h2><p className="text-gray-400 text-sm mb-6">Diagnose any trade — winning or losing. The tool produces your Trade Grade.</p>
      <div className="p-6 rounded-2xl glass-card">{!autopsyComplete ? (<div className="space-y-4">
        <div className="flex items-center gap-1">{autopsySteps.map((step, i) => (<div key={i} className="flex-1 h-2 rounded-full transition-all" style={{ background: i < autopsyStep ? step.color + '60' : i === autopsyStep ? step.color + '30' : 'rgba(255,255,255,0.05)' }} />))}</div>
        <div className="p-4 rounded-xl border" style={{ borderColor: autopsySteps[autopsyStep].color + '30' }}>
          <div className="flex items-center gap-2 mb-4"><span className="text-lg">{autopsySteps[autopsyStep].icon}</span><div><p className="text-[10px] uppercase tracking-widest font-bold" style={{ color: autopsySteps[autopsyStep].color }}>Step {autopsySteps[autopsyStep].id} of 7</p><p className="text-sm font-bold text-white">{autopsySteps[autopsyStep].title}</p></div></div>
          <p className="text-sm text-gray-300 mb-4">{autopsySteps[autopsyStep].question}</p>
          <div className="space-y-2 mb-4">{autopsySteps[autopsyStep].options.map(opt => (<button key={opt.value} onClick={() => handleAutopsyAnswer(opt.value)} className={`w-full text-left p-3 rounded-xl text-sm transition-all ${autopsyAnswers[autopsyStep] === opt.value ? 'border-2 bg-white/[0.04]' : 'bg-white/[0.04] border border-white/[0.08] hover:bg-white/[0.07]'}`} style={autopsyAnswers[autopsyStep] === opt.value ? { borderColor: autopsySteps[autopsyStep].color + '60', color: autopsySteps[autopsyStep].color } : { color: '#d1d5db' }}><span className="flex items-center gap-2"><span className={`w-5 h-5 rounded flex-shrink-0 flex items-center justify-center text-[10px] font-bold ${opt.score === 3 ? 'bg-green-500/20 text-green-400' : opt.score === 2 ? 'bg-amber-500/20 text-amber-400' : opt.score === 1 ? 'bg-orange-500/20 text-orange-400' : 'bg-red-500/20 text-red-400'}`}>{opt.score}</span>{opt.label}</span></button>))}</div>
          <div className="mb-4"><p className="text-xs text-gray-500 mb-1.5">{autopsySteps[autopsyStep].followUp}</p><textarea value={autopsyNotes[autopsyStep]} onChange={e => { const n = [...autopsyNotes]; n[autopsyStep] = e.target.value; setAutopsyNotes(n); }} placeholder="Your reasoning (optional)..." className="w-full p-3 rounded-xl bg-white/[0.03] border border-white/10 text-sm text-white placeholder:text-gray-600 focus:border-amber-500/30 outline-none resize-none" rows={2} /></div>
          {autopsyAnswers[autopsyStep] && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="p-3 rounded-lg bg-white/[0.02] mb-4"><p className="text-xs leading-relaxed" style={{ color: autopsySteps[autopsyStep].color }}>{autopsySteps[autopsyStep].insight}</p></motion.div>)}
          <div className="flex gap-3">{autopsyStep > 0 && (<button onClick={() => setAutopsyStep(s => s - 1)} className="px-4 py-2.5 rounded-xl bg-white/[0.05] border border-white/10 text-xs font-semibold text-gray-300">&larr;</button>)}{autopsyAnswers[autopsyStep] && (<button onClick={nextAutopsyStep} className="flex-1 px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-accent-500 text-white text-sm font-bold active:scale-95 transition-transform">{autopsyStep < 6 ? `Step ${autopsyStep + 2}: ${autopsySteps[autopsyStep + 1].title} →` : 'Generate Trade Grade →'}</button>)}</div>
        </div>
      </div>) : (<motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="space-y-4">
        <div className="p-6 rounded-xl text-center border" style={{ borderColor: getAutopsyGrade().color + '30', background: getAutopsyGrade().color + '08' }}><p className="text-6xl font-black mb-2" style={{ color: getAutopsyGrade().color }}>{getAutopsyGrade().grade}</p><p className="text-sm font-bold mb-1" style={{ color: getAutopsyGrade().color }}>{getAutopsyGrade().label}</p><p className="text-xs text-gray-400 mb-3">{getAutopsyScore()}/21 points</p><p className="text-xs text-gray-400 max-w-md mx-auto">{getAutopsyGrade().feedback}</p></div>
        <div className="space-y-2"><p className="text-xs font-bold text-gray-300 uppercase tracking-widest">Step-by-Step Breakdown</p>{autopsySteps.map((step, i) => { const score = getStepScore(i); const ans = autopsyAnswers[i]; const opt = step.options.find(o => o.value === ans); return (<div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"><span className="text-sm">{step.icon}</span><div className="flex-1 min-w-0"><p className="text-xs font-bold text-gray-300">{step.title}</p><p className="text-[11px] text-gray-500 truncate">{opt?.label || '—'}</p></div><span className={`text-sm font-black ${score === 3 ? 'text-green-400' : score === 2 ? 'text-amber-400' : score === 1 ? 'text-orange-400' : 'text-red-400'}`}>{score}/3</span></div>); })}</div>
        <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/10"><p className="text-xs font-bold text-red-400 mb-1">🎯 Priority Fix: {getWeakestStep()}</p><p className="text-xs text-gray-400">Focus here for your next 10 trades.</p></div>
        <button onClick={() => { setAutopsyStep(0); setAutopsyAnswers(autopsySteps.map(() => null)); setAutopsyNotes(autopsySteps.map(() => '')); setAutopsyComplete(false); }} className="w-full px-4 py-2.5 rounded-xl bg-white/[0.05] border border-white/10 text-xs font-semibold text-gray-300 hover:bg-white/[0.07]">Autopsy Another Trade</button>
      </motion.div>)}</div></motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">06 &mdash; Winners Need Autopsies Too</p><h2 className="text-2xl font-extrabold mb-4">Why a Winning Trade Can Get an F</h2><div className="p-6 rounded-2xl glass-card"><p className="text-sm text-gray-400 leading-relaxed mb-4">A winning trade with process errors is <strong className="text-white">more dangerous</strong> than a losing trade with perfect process. The profit <strong className="text-white">reinforces the bad behaviour</strong>.</p><div className="grid grid-cols-2 gap-3"><div className="p-3 rounded-xl bg-green-500/5 border border-green-500/10"><p className="text-xs font-bold text-green-400 mb-1">A-Grade Loss</p><p className="text-[11px] text-gray-400">Perfect process, stop hit. Bad luck. Keep trading like this.</p></div><div className="p-3 rounded-xl bg-red-500/5 border border-red-500/10"><p className="text-xs font-bold text-red-400 mb-1">F-Grade Win</p><p className="text-[11px] text-gray-400">No stop, revenge entry, doubled size. Won anyway. Ticking time bomb.</p></div></div></div></motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">07 &mdash; Lesson Quality Hierarchy</p><h2 className="text-2xl font-extrabold mb-4">How to Write Lessons That Change Your Trading</h2><div className="space-y-3">{lessonTiers.map(item => (<div key={item.tier}><button onClick={() => toggle(`lt-${item.tier}`)} className="w-full text-left p-4 rounded-xl glass hover:bg-white/5 transition-all flex items-center justify-between"><span className="text-sm font-bold" style={{ color: item.color }}>{item.tier}: &ldquo;{item.example}&rdquo;</span><ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${openSections[`lt-${item.tier}`] ? 'rotate-180' : ''}`} /></button><AnimatePresence>{openSections[`lt-${item.tier}`] && (<motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="p-4 rounded-b-xl bg-white/[0.02] border-x border-b border-white/[0.05]"><p className="text-sm text-gray-400">{item.problem}</p></div></motion.div>)}</AnimatePresence></div>))}</div></motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">08 &mdash; Common Autopsy Mistakes</p><h2 className="text-2xl font-extrabold mb-4">4 Ways Traders Sabotage Reviews</h2><div className="space-y-3">{autopsyMistakes.map((item, i) => (<div key={i}><button onClick={() => toggle(`am-${i}`)} className="w-full text-left p-4 rounded-xl glass hover:bg-white/5 transition-all flex items-center justify-between"><span className="text-sm font-bold text-gray-200">{item.title}</span><ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${openSections[`am-${i}`] ? 'rotate-180' : ''}`} /></button><AnimatePresence>{openSections[`am-${i}`] && (<motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="p-4 rounded-b-xl bg-white/[0.02] border-x border-b border-white/[0.05]"><p className="text-xs text-red-400 mb-2">&#10060; {item.mistake}</p><p className="text-xs text-green-400">&#10004; {item.fix}</p></div></motion.div>)}</AnimatePresence></div>))}</div></motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">09 &mdash; Cheat Sheet</p><h2 className="text-2xl font-extrabold mb-4">Autopsy Quick Reference</h2><div className="p-6 rounded-2xl glass-card space-y-3">
        <div className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"><p className="text-sm"><strong className="text-amber-400">7 STEPS</strong> <span className="text-gray-500">=</span> <span className="text-gray-400">Bias &rarr; Setup &rarr; Trigger &rarr; Stop &rarr; Management &rarr; Emotion &rarr; Lesson. Every trade.</span></p></div>
        <div className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"><p className="text-sm"><strong className="text-red-400">AUTO-FAIL</strong> <span className="text-gray-500">=</span> <span className="text-gray-400">No stop = F. Tilted = F. These override all other scores.</span></p></div>
        <div className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"><p className="text-sm"><strong className="text-[#ec4899]">#1 KILLER</strong> <span className="text-gray-500">=</span> <span className="text-gray-400">Emotion (35%) beats strategy (18%) as the top failure point. Fix psychology first.</span></p></div>
        <div className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"><p className="text-sm"><strong className="text-[#26A69A]">A-TIER LESSON</strong> <span className="text-gray-500">=</span> <span className="text-gray-400">Specific action + sample size + measurement. &ldquo;Be disciplined&rdquo; is F-tier.</span></p></div>
        <div className="p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"><p className="text-sm"><strong className="text-[#3b82f6]">CADENCE</strong> <span className="text-gray-500">=</span> <span className="text-gray-400">Every trade for first 100. Then weekly: best win, worst loss, any rule break.</span></p></div>
      </div></motion.div></section>

      {/* S10 — Game */}
      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">10 &mdash; Test Your Understanding</p><h2 className="text-2xl font-extrabold mb-2">Trade Autopsy Game</h2><p className="text-gray-400 text-sm mb-6">5 autopsy cases. Diagnose where each trade failed.</p>
      <div className="p-6 rounded-2xl glass-card"><div className="flex items-center justify-between mb-4"><span className="text-xs font-bold text-amber-400">Round {gameRound + 1} of {gameRounds.length}</span><span className="text-xs font-mono text-gray-500">{gameScore}/{gameRounds.length} correct</span></div><p className="text-sm text-gray-300 leading-relaxed mb-5" dangerouslySetInnerHTML={{ __html: gameRounds[gameRound].scenario }} /><div className="space-y-2">{gameRounds[gameRound].options.map((opt, oi) => { const answered = gameAnswers[gameRound] !== null; const selected = gameAnswers[gameRound] === oi; const isCorrect = opt.correct; let cls = 'bg-white/[0.04] border border-white/[0.08] hover:bg-white/[0.07]'; if (answered && selected && isCorrect) cls = 'bg-green-500/10 border border-green-500/30'; if (answered && selected && !isCorrect) cls = 'bg-red-500/10 border border-red-500/30'; if (answered && !selected && isCorrect) cls = 'bg-green-500/5 border border-green-500/20'; return (<div key={oi}><button onClick={() => handleGameAnswer(oi)} disabled={answered} className={`w-full text-left p-4 rounded-xl transition-all text-sm ${cls}`}><span dangerouslySetInnerHTML={{ __html: opt.text }} /></button>{answered && selected && (<motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="mt-1 p-3 rounded-lg bg-white/[0.02]"><p className={`text-xs leading-relaxed ${isCorrect ? 'text-green-400' : 'text-red-400'}`} dangerouslySetInnerHTML={{ __html: `${isCorrect ? '✓' : '✗'} ${opt.explain}` }} /></motion.div>)}</div>); })}</div>{gameAnswers[gameRound] !== null && gameRound < gameRounds.length - 1 && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-5"><button onClick={() => setGameRound(r => r + 1)} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-accent-500 text-white text-sm font-bold active:scale-95 transition-transform">Next Round &rarr;</button></motion.div>)}{gameAnswers[gameRound] !== null && gameRound === gameRounds.length - 1 && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-5 p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-center"><p className="text-lg font-extrabold text-amber-400">{gameScore}/{gameRounds.length} Correct</p><p className="text-xs text-gray-400 mt-1">{gameScore >= 4 ? 'Excellent — forensic precision.' : gameScore >= 3 ? 'Good — review symptom vs root cause.' : 'Re-read the 7 Steps and focus on identifying the FIRST point of failure.'}</p></motion.div>)}</div></motion.div></section>

      {/* S11 — Quiz + Certificate */}
      <section className="max-w-2xl mx-auto px-5 py-16"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-bold tracking-widest uppercase text-amber-400/60 mb-3">11 &mdash; Knowledge Check</p><h2 className="text-2xl font-extrabold mb-6">Final Quiz &mdash; 8 Questions</h2>
      <div className="space-y-6">{quizQuestions.map((q, qi) => (<div key={qi} className="p-5 rounded-2xl glass-card"><p className="text-xs font-semibold tracking-widest uppercase text-amber-400 mb-2">Question {qi + 1} of {quizQuestions.length}</p><p className="text-sm font-semibold text-white mb-4">{q.q}</p><div className="space-y-2">{q.opts.map((opt, oi) => { const answered = quizAnswers[qi] !== null; const selected = quizAnswers[qi] === oi; const isCorrect = oi === q.correct; let cls = 'bg-white/[0.04] border border-white/[0.08] hover:bg-white/[0.07]'; if (answered && selected && isCorrect) cls = 'bg-green-500/10 border border-green-500/30'; if (answered && selected && !isCorrect) cls = 'bg-red-500/10 border border-red-500/30'; if (answered && !selected && isCorrect) cls = 'bg-green-500/5 border border-green-500/20'; return <button key={oi} onClick={() => handleQuizAnswer(qi, oi)} disabled={answered} className={`w-full text-left p-3 rounded-xl transition-all text-sm ${cls}`}>{opt}</button>; })}</div>{quizAnswers[qi] !== null && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-3 p-3 rounded-lg bg-white/[0.02]"><p className="text-xs text-amber-400" dangerouslySetInnerHTML={{ __html: `<span class="font-bold">&#9989;</span> ${q.explain}` }} /></motion.div>)}</div>))}</div>
      {quizDone && (<motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mt-8 text-center"><p className="text-3xl font-extrabold mb-2">{quizScoreVal}%</p><p className="text-sm text-gray-400">{quizScoreVal >= 66 ? 'You passed! Certificate unlocked below.' : 'You need 66% to earn the certificate.'}</p></motion.div>)}
      {certUnlocked && (<motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.8 }} className="mt-10"><div className="max-w-md mx-auto p-10 rounded-3xl relative overflow-hidden border border-amber-500/20" style={{ background: 'linear-gradient(145deg, rgba(13,19,32,1), rgba(20,28,46,1))' }}><div className="absolute inset-0 bg-[conic-gradient(from_0deg,transparent,rgba(245,158,11,0.06),transparent,rgba(139,92,246,0.04),transparent)] animate-spin" style={{ animationDuration: '12s' }} /><div className="relative z-10 text-center"><div className="w-[72px] h-[72px] mx-auto mb-5 rounded-full bg-gradient-to-br from-red-500 via-amber-500 to-purple-500 flex items-center justify-center text-3xl shadow-lg shadow-red-500/30">🔬</div><p className="text-xs tracking-widest uppercase text-gray-500 mb-3">Certificate of Completion</p><p className="text-sm text-gray-400">Has successfully completed<br /><strong className="text-white">Level 7: The Trade Autopsy</strong><br />at ATLAS Academy by Interakktive</p><p className="bg-gradient-to-r from-red-400 via-amber-400 to-purple-400 bg-clip-text text-transparent font-bold text-lg mb-1 mt-4" style={{ WebkitTransform: 'translateZ(0)' }}>&mdash; Trade Forensic &mdash;</p><p className="font-mono text-[9px] text-amber-600/60 tracking-wider uppercase">PRO-CERT-L7.10-{Math.random().toString(36).substring(2, 10).toUpperCase()}</p></div></div></motion.div>)}</motion.div></section>

      <section className="max-w-2xl mx-auto px-5 py-20 text-center"><Link href="/academy" className="inline-flex items-center gap-2.5 px-8 py-4 rounded-xl bg-gradient-to-r from-amber-500 to-accent-500 hover:from-amber-600 hover:to-accent-600 text-white font-bold text-sm shadow-lg shadow-amber-500/20 transition-all active:scale-95">&larr; Back to Academy</Link></section>
    </div>
  );
}
